### PR TITLE
Remove Ackermann files and package, depend on hydra-battles

### PR DESCRIPTION
**Pull request by palmskog**
We'll see how it works now with depending on hydra-battles...

### CODE REVIEW

**Comment by Zimmi48** [comment]
It might be worth starting a changelog file now, especially to note this big change.

**Comment by Casteran** [comment]
In order to build Goedel (by make, after cloning), I added  to _CoqProject the line
-R ../hydra-battles/theories/ordinals hydras

Is this the right thing to do ? May be it depends too much on my local installation ?

**Comment by palmskog** [comment]
@Casteran until we have better support for compositional builds in Coq with Dune, what you propose is probably the best way to do local development with dependencies. However, the modified `_CoqProject` shouldn't be committed to the repo.

**Comment by Casteran** [comment]
I created a (local) branch local-dev for testing Goedel with the local installation of hydra-battles.
Thus  _CoqProject will remain unchanged in the repo.

**Pull request merged**
