### PR TITLE
New stuff

### PR DESCRIPTION
**Pull request by palmskog**
This is a draft with new primitive recursive function examples from @Casteran and split up into a Gödel part and an Ackermann part for easier reuse. At least a draft PR is needed to get continuous integration.

### CODE REVIEW

**Comment by palmskog** [comment]
@Casteran you can now keep pushing changes to the `new-stuff` branch until you think it is ready to be merged - then you change the status of this pull request from "Draft" to "Ready for review". Our default for continuous integration is to only run when there is a pull request.

**Comment by Casteran** [comment]
OK, since Ackermann is a big library (39 .v files, >= 30K lines), I will propose several PRs (one per big revised file).
I’m planning to propose also two non-trivial exercises (which may require a lot of lemmas). It would be nice to ask for contributions(in the form of PRs)  in order to publish their solution.

- Prove that the Fibonacci function is PR
- Prove that the Ackermann function is not PR

I can add two files Fib_project.v  and Ack_project.v (in the style of coq-art’s exercises, and an advertising in README.md

**Comment by palmskog** [comment]
@Casteran so you mean we should merge this pull request now and you will do additional ones later?

The advantage of merging the current changes (the split packages) now is that we can start to use `coq-ackermann` as a dependency in `coq-hydra-battles`, and continuous integration will check with the latest Ackermann version via Git whenever you commit to Hydra Battles.

**Comment by Casteran** [comment]
Well, that would be fine.

**Pull request merged**
